backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads/"
public_folder: ""

collections:
  - name: "photos"
    label: "Photos"
    folder: "content/photos"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "videos"
    label: "Videos"
    folder: "content/videos"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Source", name: "src", widget: "text"}